name: Auto validate automation PRs

on:
  pull_request_target:
    types: [opened, synchronize, reopened, ready_for_review, labeled]

permissions:
  contents: write
  pull-requests: write

jobs:
  approve_and_enable_automerge:
    if: >
      github.event.pull_request.head.repo.full_name == github.repository &&
      startsWith(github.event.pull_request.head.ref, 'bot/ingest-') &&
      contains(join(github.event.pull_request.labels.*.name, ','), 'automerge')
    runs-on: ubuntu-latest
    steps:
      - name: Approve PR with gh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          REPO: ${{ github.repository }}
        run: |
          gh pr review "$PR_NUMBER" --repo "$REPO" --approve --body "Auto approved by CI for automation PR"

      - name: Enable automerge
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          REPO: ${{ github.repository }}
        run: |
          gh pr merge "$PR_NUMBER" --repo "$REPO" --auto --squash
