name: Auto-validate automation PRs

on:
  pull_request_target:
    types: [opened, synchronize, reopened, ready_for_review, labeled]

permissions:
  contents: write
  pull-requests: write

jobs:
  approve_and_enable_automerge:
    # Only PRs from same repo, branch starts with bot/ingest-, and has label "automerge"
    if: >
      github.event.pull_request.head.repo.full_name == github.repository &&
      startsWith(github.event.pull_request.head.ref, 'bot/ingest-') &&
      contains(join(github.event.pull_request.labels.*.name, ','), 'automerge')
    runs-on: ubuntu-latest
    steps:
      - name: Auto-approve
        uses: peter-evans/approve-pull-request@v6
        with:
          token: ${{ github.token }}
          pull-request-number: ${{ github.event.pull_request.number }}
          review-message: "Auto-approved by bot."

      - name: Enable auto-merge (rebase)
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ github.token }}
          pull-request-number: ${{ github.event.pull_request.number }}
          merge-method: rebase
