name: Auto-approve & auto-merge automation PRs

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review, labeled]
  pull_request_target:
    types: [opened, synchronize, reopened, ready_for_review, labeled]
  workflow_dispatch: {}

permissions:
  contents: write
  pull-requests: write

jobs:
  approve_and_enable_automerge:
    runs-on: ubuntu-latest
    steps:
      - name: Debug event
        run: |
          echo "event=${{ github.event_name }}"
          echo "action=${{ github.event.action }}"
          echo "repo=${{ github.repository }}"
          echo "head.repo=${{ github.event.pull_request.head.repo.full_name }}"
          echo "head.ref=${{ github.event.pull_request.head.ref }}"
          echo "labels=${{ join(github.event.pull_request.labels.*.name, ',') }}"

      - name: Gate for bot branches
        id: gate
        run: |
          BRANCH="${{ github.event.pull_request.head.ref || '' }}"
          if [[ "$BRANCH" == bot/ingest-* ]]; then
            echo "ok=true" >> "$GITHUB_OUTPUT"
          else
            echo "ok=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Add automerge label (idempotent)
        if: steps.gate.outputs.ok == 'true'
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ github.token }}
          number: ${{ github.event.pull_request.number }}
          labels: automerge

      - name: Auto-approve
        if: steps.gate.outputs.ok == 'true'
        uses: peter-evans/approve-pull-request@v6
        with:
          token: ${{ github.token }}
          pull-request-number: ${{ github.event.pull_request.number }}
          review-message: "Auto-approved by CI for automation PR."

      - name: Enable auto-merge (squash)
        if: steps.gate.outputs.ok == 'true'
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ github.token }}
          pull-request-number: ${{ github.event.pull_request.number }}
          merge-method: squash
